name: zyh_flutter_components
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # 图片压缩
  flutter_native_image: ^0.0.5+2
  # 网络图片缓存
  cached_network_image: ^2.2.0+1
  # 缓存文件管理
  flutter_cache_manager: ^1.4.0
  # 录视频
  camera: ^0.5.8+2
  # 放视频
  video_player: 0.10.11+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
